### ISSUE TITLE
HIGHS-ipm incorrectly reports infeasibility on unbounded problem

### ISSUE THREAD

**Issue by mdhaber** [scipy/HiGHS#43]
Example:
```
import numpy as np
from scipy.optimize import linprog
options={}
    
for method in ['interior-point', 'highs', 'highs-ipm', 'highs-simplex']:
    np.random.seed(0)
    m_eq, m_ub, n = 10, 20, 50
    c = np.random.rand(n)-0.5
    A_ub = np.random.rand(m_ub, n)-0.5
    b_ub = np.random.rand(m_ub)-0.5
    A_eq = None # np.random.rand(m_eq, n)-0.5
    b_eq = None # np.random.rand(m_eq)-0.5
    lb = -np.random.rand(n)
    ub = np.random.rand(n)
    lb[lb < -np.random.rand()] = -np.inf
    ub[ub > np.random.rand()] = np.inf
    bounds = np.vstack((lb, ub)).T
    res = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq,
                  bounds=bounds, method=method, options=options)
    print(method)
    print(res)
    input("Press any key to continue.")
    print("")
```
`highs-ipm` reports that the problem is infeasible, but the other solvers report that it is unbounded.

**Comment by mckib2** [comment]
This is indeed an upstream problem, here's an MPS that recreates it:
[status_mismatch.mps.txt](https://github.com/mckib2/HiGHS/files/4686129/status_mismatch.mps.txt)

See upstream issue: https://github.com/ERGO-Code/HiGHS/issues/373

Since this is IPX and we know that they do not provide support for every issue there, I've asked if this is a serious enough issue to warrant worry or whether it's an edge case that we can make note of and largely ignore

**Comment by mckib2** [comment]
This is now fixed in HiGHS master so should get to us with https://github.com/scipy/scipy/pull/15217.  Since there's nothing to do here, I'll close this issue
